name: build
run-name: ${{ github.event_name == 'repository_dispatch' && format('🌙 Nightly build 🚀 {0}-{1}-{2}', github.event.client_payload.tag, github.event.client_payload.date, github.event.client_payload.sha) || '🚀 Build' }}

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ build-nightly ]

env:
  REPO: 'elfmz/far2l'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date.outputs.date }}
      sha: ${{ steps.sha.outputs.sha }}
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date -u +%Y-%m-%d)" >> $GITHUB_OUTPUT

      - name: Get short SHA
        id: sha
        run: echo "sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Get default tag
        id: tag
        run: echo "tag=$(date -u +%Y.%m.%d)" >> $GITHUB_OUTPUT

  build-portable-glibc:
    name: build ${{ matrix.arch }}-glibc
    needs: prepare
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x64
            distro: ubuntu
            version: '20.04'
    container: ${{ matrix.distro }}:${{ matrix.version }}
    steps:
      - name: Add build dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
          PACKAGES: >
            7zip ca-certificates ccache cmake file g++ git libarchive-dev libneon27-dev libnfs-dev libsmbclient-dev
            libssh-dev libuchardet-dev libxml2-dev libxi-dev libtree make makeself patch patchelf quilt wget xz-utils
        run: |
          if [ "${{ matrix.distro }}" = "ubuntu" ]; then
            echo "deb [trusted=yes] http://ppa.launchpad.net/far2l-team/tools/ubuntu bionic main" | tee /etc/apt/sources.list.d/far2l-team.list
            echo "deb [trusted=yes] http://ppa.launchpad.net/git-core/ppa/ubuntu bionic main" | tee /etc/apt/sources.list.d/git-core.list
            apt update -qq && apt install -y --no-install-recommends ${{ env.PACKAGES }}
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout far2l
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO }}
          path: far2l

      - name: Setup ccache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.ccache
          key: ccache-${{ matrix.distro }}-${{ matrix.version }}-${{ matrix.arch }}-${{ github.event_name == 'repository_dispatch' && github.event.client_payload.sha || github.run_id }}
          restore-keys: ccache-${{ matrix.distro }}-${{ matrix.version }}-${{ matrix.arch }}-

      - name: Build far2l
        env:
          DATE: ${{ needs.prepare.outputs.date }}
          SHA: ${{ needs.prepare.outputs.sha }}
          TAG: ${{ needs.prepare.outputs.tag }}
          STANDALONE: true
          WXGUI: false
          ADD_7Z: false
        run: |
          export VERSION=${TAG}.git$(date -u -d "$DATE" +%Y%m%d)
          export PKG_NAME=far2l_${VERSION}-$(uname -m)-glibc
          bash build_far2l.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: far2l-${{ matrix.distro }}-${{ matrix.version }}-${{ matrix.arch }}
          path: ./**/far2l*.tar*
          if-no-files-found: error

  build-portable-musl:
    name: build ${{ matrix.arch }}-musl
    needs: prepare
    #if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
    if: false
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch:
          - x86_64
          #- x86
          #- aarch64
          #- armhf
          #- armv7
          # - ppc64le
          # - s390x
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout far2l
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO }}
          path: far2l

      - name: Setup ccache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.ccache
          key: ccache-${{ matrix.arch }}-${{ github.event_name == 'repository_dispatch' && github.event.client_payload.sha || github.run_id }}
          restore-keys: ccache-${{ matrix.arch }}-

      - name: Setup Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          branch: v3.18
          arch: ${{ matrix.arch }}
          packages: >
            bash build-base ccache cmake coreutils findutils gawk git grep libarchive-dev libnfs-dev libssh-dev libtree
            libxi-dev linux-headers neon-dev patchelf perl samba-dev tar uchardet-dev wget libxml2-dev xz
          shell-name: alpine.sh

      - name: Add extra build-deps to chroot
        shell: alpine.sh --root {0}
        run: |
          apk add --no-progress makeself --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing
          apk add --no-progress quilt --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community

      - name: Build far2l inside chroot
        env:
          DATE: ${{ needs.prepare.outputs.date }}
          SHA: ${{ needs.prepare.outputs.sha }}
          TAG: ${{ needs.prepare.outputs.tag }}
          ARCH: ${{ matrix.arch }}
          STANDALONE: true
          WXGUI: false
        shell: alpine.sh {0}
        run: |
          export VERSION=${TAG}.git$(date -u -d "$DATE" +%Y%m%d)
          export PKG_NAME=far2l_${VERSION}-${ARCH}-musl
          bash build_far2l.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: far2l-${{ matrix.arch }}
          path: ./**/far2l*.tar*
          if-no-files-found: error

  release:
    name: Update release
    needs: [ prepare, build-portable-glibc ]
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      DATE: ${{ needs.prepare.outputs.date }}
      SHA: ${{ needs.prepare.outputs.sha }}
      TAG: ${{ needs.prepare.outputs.tag }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Upload release assets
        id: assets
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          only-when-changed: false
          prerelease: false
          tag_name: latest
          name: ${{ env.TAG }}-${{ env.DATE }}
          body: |
            Build: ${{ env.TAG }}-${{ env.DATE }}-${{ env.SHA }}
            Commit: ${{ github.sha }}
          files: |
            ./**/far2l*.run.tar
